
version: "2.1"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    networks:
      - db_net
    env_file:
      - configs/postgres_env

  django:
    build: configs
    container_name: django
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && gunicorn hello.wsgi -b 0.0.0.0:8000"
    env_file:
      - configs/postgres_env
    depends_on:
      - postgres

    volumes_from:
      - postgres
    volumes:
      - ./hello:/workdir
    networks:
      - db_net
      - django_net

  nginx:
    image: "nginx:1.13.5"
    ports:
      - "8080:80"
    volumes:
      - ./nginx_conf/:/etc/nginx/conf.d
    networks:
      - django_net
    depends_on: 
      - django
networks:
  db_net:
    driver: bridge
  django_net:
    driver: bridge
